#
# Copyright (C) 2024 Temmi Pietsch - All Rights Reserved
#
# You may not use, distribute or modify this code without the explicitly
# permission of the author.
#

services:
  server:
    container_name: gjshare_pics_web
    restart: always
    hostname: gjshare.pics
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "95:95"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gjshare_pics_web.entrypoints=web"
      - "traefik.http.routers.gjshare_pics_web.rule=Host(`gjshare.pics`) || Host(`www.gjshare.pics`)"
      - "traefik.http.middlewares.gjshare_pics_web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gjshare_pics_web.middlewares=gjshare_pics_web-https-redirect"
      - "traefik.http.routers.gjshare_pics_web-secure.entrypoints=websecure"
      - "traefik.http.routers.gjshare_pics_web-secure.rule=Host(`gjshare.pics`) || Host(`www.gjshare.pics`)"
      - "traefik.http.routers.gjshare_pics_web-secure.tls=true"
      - "traefik.http.routers.gjshare_pics_web-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gjshare_pics_web-secure.service=gjshare_pics_web"
      - "traefik.http.services.gjshare_pics_web.loadbalancer.server.port=95"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default

networks:
  proxy:
    external: true
  default:
    driver: bridge
