################################################################################
# gj-sharepic-creator
# Copyright (c) 2025 temmiland
#
# Licensed under the Affero General Public License (AGPL) Version 3.0;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     https://gjshare.pics/license
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# Affero General Public License for more details.
#
# You should have received a copy of the Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################

version: '3.8'
services:
  server:
    container_name: gjshare_pics_web
    restart: always
    hostname: gjshare.pics
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "95:95"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gjshare_pics_web.entrypoints=web"
      - "traefik.http.routers.gjshare_pics_web.rule=Host(`gjshare.pics`) || Host(`www.gjshare.pics`)"
      - "traefik.http.middlewares.gjshare_pics_web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gjshare_pics_web.middlewares=gjshare_pics_web-https-redirect"
      - "traefik.http.routers.gjshare_pics_web-secure.entrypoints=websecure"
      - "traefik.http.routers.gjshare_pics_web-secure.rule=Host(`gjshare.pics`) || Host(`www.gjshare.pics`)"
      - "traefik.http.routers.gjshare_pics_web-secure.tls=true"
      - "traefik.http.routers.gjshare_pics_web-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gjshare_pics_web-secure.service=gjshare_pics_web"
      - "traefik.http.services.gjshare_pics_web.loadbalancer.server.port=95"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default

networks:
  proxy:
    external: true
  default:
    driver: bridge
