import type { SharePicTemplate } from '@/types/template';

export const defaultTemplates: SharePicTemplate[] = [
	{
		id: 'titleOnly',
		name: 'Überschrift (opt. Piktogramm)',
		version: 1,
		templateType: 'sharepic',
		canvas: {
			width: 360,
			height: 450,
			colorSetName: 'Apricot',
			highlightColorName: 'Light Green',
			backgroundImage: null,
			backgroundPositionValue: 'top left',
			backgroundBlur: 0.2,
			backgroundBrightness: 100,
		},
		elements: [
			{
				id: 'logo-1',
				type: 'logo',
				x: 12,
				y: 405,
				visible: true,
				localGroup: 'Leipzig',
			},
			{
				id: 'arrow-1',
				type: 'arrow',
				x: 308,
				y: 398,
				visible: true,
				size: 50,
			},
			{
				id: 'heading-1',
				type: 'heading',
				x: 30,
				y: 235,
				visible: true,
				content: ['*Menschen', 'retten statt', 'Abschottung!'],
				fontSize: 3.75,
				width: 297,
			},
			{
				id: 'pictogram-1',
				type: 'pictogram',
				x: 75,
				y: 50,
				visible: true,
				pictogramName: 'Banner',
				size: 18,
			},
		],
	},
	{
		id: 'titleAndText',
		name: 'Überschrift & Text',
		version: 1,
		templateType: 'sharepic',
		canvas: {
			width: 360,
			height: 450,
			colorSetName: 'Green',
			highlightColorName: 'Light Green',
			backgroundImage: null,
			backgroundPositionValue: 'top left',
			backgroundBlur: 0.2,
			backgroundBrightness: 100,
		},
		elements: [
			{
				id: 'arrow-1',
				type: 'arrow',
				x: 308,
				y: 398,
				visible: true,
				size: 50,
			},
			{
				id: 'heading-1',
				type: 'heading',
				x: 29,
				y: 75,
				visible: true,
				content: ['*Kein Ausbau', 'fossiler Infrastruktur!'],
				fontSize: 2.6,
				width: 297,
			},
			{
				id: 'text-1',
				type: 'text',
				x: 29,
				y: 155,
				visible: true,
				content: [
					'In den letzten Jahrzehnten ist die Energieversorgung in Deutschland auf Energieimporte aus Russland in Form von Erdgas aufgebaut worden. Das hat sich durch den brutalen Überfall Russlands auf die Ukraine geändert. Die große Abhängigkeit von fossilen Energien ist der Grund für die Energiekrise. Ein weiterer Ausbau von LNG-Terminals kann daher keine Lösung sein!',
				],
				width: 297,
			},
		],
	},
	{
		id: 'event',
		name: 'Veranstaltung (opt. Piktogramm)',
		version: 1,
		templateType: 'sharepic',
		canvas: {
			width: 360,
			height: 450,
			colorSetName: 'Black',
			highlightColorName: 'Light Green',
			backgroundImage: './event_bg.jpg',
			backgroundPositionValue: 'top left',
			backgroundBlur: 0,
			backgroundBrightness: 100,
		},
		elements: [
			{
				id: 'logo-1',
				type: 'logo',
				x: 12,
				y: 405,
				visible: true,
				localGroup: 'Leipzig',
			},
			{
				id: 'heading-1',
				type: 'heading',
				x: 29,
				y: 75,
				visible: true,
				content: ['*Weihnachts-', 'feier'],
				fontSize: 3.75,
				width: 297,
			},
			{
				id: 'text-1',
				type: 'text',
				x: 29,
				y: 175,
				visible: true,
				content: [
					'%Mit leckeren Plätzchen, Punsch und Pub-Quiz feiern wir die Weihnachtszeit.%',
					'%🗓️ Dienstag, 12.12.2025 – 18:30 Uhr%',
					'%📍 Grünen Quartier, Heinrichstraße 9, Leipzig%',
				],
				width: 297,
			},
		],
	},
	{
		id: 'textOnly',
		name: 'Text (opt. Piktogramm)',
		version: 1,
		templateType: 'sharepic',
		canvas: {
			width: 360,
			height: 450,
			colorSetName: 'Lavendel',
			highlightColorName: 'Light Green',
			backgroundImage: null,
			backgroundPositionValue: 'top left',
			backgroundBlur: 0.2,
			backgroundBrightness: 100,
		},
		elements: [
			{
				id: 'arrow-1',
				type: 'arrow',
				x: 308,
				y: 398,
				visible: true,
				size: 50,
			},
			{
				id: 'text-1',
				type: 'text',
				x: 29,
				y: 50,
				visible: true,
				content: [
					'Ziel waren stets Gay Bars in Greenwich Village, einem Stadtteil New Yorks. Dieses Mal lehnte sich die Community aber gegen die Polizeigewalt auf. Die Polizisten verbarrikadierten sich in der Bar, während Hunderte von Menschen protestierten. Die Aufstände vor dem Stonewall Inn waren eines der ersten Ereignisse, bei dem Lesben, Schwule, trans* Personen und andere Gruppen gemeinsam kämpften!',
				],
				width: 297,
			},
		],
	},
	{
		id: 'pictogramOnly',
		name: 'Piktogramm',
		version: 1,
		templateType: 'sharepic',
		canvas: {
			width: 360,
			height: 450,
			colorSetName: 'Pink',
			highlightColorName: 'Light Green',
			backgroundImage: null,
			backgroundPositionValue: 'top left',
			backgroundBlur: 0.2,
			backgroundBrightness: 100,
		},
		elements: [
			{
				id: 'arrow-1',
				type: 'arrow',
				x: 308,
				y: 398,
				visible: true,
				size: 50,
			},
			{
				id: 'pictogram-1',
				type: 'pictogram',
				x: 95,
				y: 125,
				visible: true,
				pictogramName: 'Streikfaust',
				size: 18,
			},
		],
	},
];
